---
email: john@jr0cket.co.uk
author: jr0cket
author_github: jr0cket
title: ClojureBridge London
tagline: ClojureBridge London
nutshell: Making coding fun and inclusive with Clojure

description: |
  (A free workshop encouraging greater inclusivity into the Clojure community.  We support those new to programming up to developers new to Clojure. The interactive code snippets are powered by <a href="https://github.com/viebel/klipse">Klipse</a>.)

sass:
  sass_dir: assets/css
  style: compressed
markdown: kramdown
exclude:
    - vendor
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-utf8

